### ISSUE TITLE
Top_category_W missing in v23.02

### ISSUE THREAD

**Issue by ytakemon** [melschneider/tractability_pipeline_v2#4]
Hello, I downloaded the tractability.tsv file from version 23.2 and noticed that they do not include a Top_category_W column as written in your readme. Has this been phased out?

**Comment by hioannidis** [comment]
Hello, 

Thanks for contacting us! You can find the Top_category_W where W stands for workflow in the tsv file as category_w (category_ab, etc). Hope this helps!

Kind regards,
Harris Ioannidis (ChEMBL team)
